version: "3.9"

name: estapar-stack

networks:
  appnet:

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: estapar-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estapar
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks: [appnet]

  garage-simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-simulator
    restart: unless-stopped
    network_mode: host

  app:
    build: .
    container_name: estapar-app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estapar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectionTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SIMULATOR_BASE_URL: http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
      garage-simulator:
        condition: service_started
    networks: [appnet]
